# ~/.config/starship.toml

add_newline = false  # Inserts a blank line between shell prompts
command_timeout = 1000  # Change command timeout from 500 to 1000 ms

# Add custom formatting before other stuff
format = """$env_var $all[󰁕](49) """

# Drop ugly default prompt characters
[character]
success_symbol = ""
error_symbol = ""

# ---
# Shows whether you are inside a virtual environment
# [env_var.VIRTUAL_ENV]
# format = '[󰇙VENV󰇙](bold #FF007F) '
# disabled = false

# Shows an icon depending on what distro it is running on
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the current username
[env_var.USER]
format = '[$env_value](bold white) '
variable = "USER"
disabled = false

# Shows an icon depending on what device it is running on
[env_var.STARSHIP_DEVICE]
format = 'on [$env_value](bold yellow)'
variable = "STARSHIP_DEVICE"
disabled = false

# ---

# Shows the hostname
[hostname]
ssh_only = false
format = "[$hostname](bold yellow) "
disabled = false

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold green"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
symbol = "󰊢 "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "202"

# Shows current git status
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "202"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

# Battery
[battery]
full_symbol = "󱈏 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁻 "
empty_symbol = "󰂎 "

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold #add8e6) '

# Languages
[package]
symbol = '󰏖 '

[c]
symbol = ' '
detect_extensions = ['c', 'h', 'cpp']
format = 'via [$symbol($version )]($style)'

[python]
symbol = ' '

[nodejs]
symbol = '󰎙 '

[golang]
symbol = '󰟓 '

[lua]
symbol = '󰢱 '

[terraform]
style = "93"
format = 'with [󱁢 Terraform]($style) '
disabled = false

# Disable some modules that aren't needed anymore
[username]
disabled = true

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[ruby]
# disabled = true
symbol = " "
