# ~/.config/starship.toml

add_newline = false  # Inserts a blank line between shell prompts
command_timeout = 1000  # Change command timeout from 500 to 1000 ms

# Add custom formatting before other stuff
format = """
$env_var \
$hostname\
$directory\
$git_branch\
$git_status\

$fill\
$kubernetes\
$package\
$c\
$python\
$golang\
$nodejs\
$deno\
$lua\
$ruby\
$terraform\
${custom.mise}\

$line_break \
$battery\
$character
"""

[character]
success_symbol = '[󰁕](49)'
error_symbol = '[󰁕](bold red)'
vimcmd_symbol = '[󰁕](#d699ff)'
# vimcmd_symbol = '[](#99F6F6)'

[fill]
symbol = ' '

# Shows an icon depending on what distro it is running on
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the current username
[env_var.USER]
format = '[$env_value](bold white) '
variable = "USER"
disabled = false

# Shows an icon depending on what device it is running on
[env_var.STARSHIP_DEVICE]
format = '[$env_value](bold yellow)'
variable = "STARSHIP_DEVICE"
disabled = false

# ---

# Shows the hostname
[hostname]
ssh_only = false
format = "[$hostname](bold yellow) "
disabled = false

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold green"
home_symbol = "󰋜 ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
symbol = " "
format = "󱦰 [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "202"

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bright-black"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = " "

# Battery
[battery]
full_symbol = "󱈏 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁻 "
empty_symbol = "󰂎 "

# Shows kubernetes context and namespace
[kubernetes]
disabled = false
format = '[󱃾 $context\($namespace\)](bold #add8e6) '

# Languages
[package]
symbol = '󰏖 '
version_format = '${raw}'
format = '[$symbol$version]($style) '

[c]
symbol = ' '
detect_extensions = ['c', 'h', 'cpp', 'cc']
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[python]
symbol = ' '
version_format = '${raw}'
format = '[$symbol($version )(\($virtualenv\))]($style) '

[golang]
symbol = '󰟓 '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[nodejs]
symbol = '󰎙 '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[deno]
version_format = '${raw}'
format = '[$symbol($version )]($style)'

[lua]
symbol = '󰢱 '
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[ruby]
symbol = " "
version_format = '${raw}'
format = '[$symbol($version )]($style) '

[terraform]
style = "93"
symbol='󱁢 '
version_format = '${raw}'
format = '[$symbol($workspace )]($style) '

[custom.mise]
style = "bold yellow"
symbol = ' '
# command = 'mise set | wc -l'
# when = ''' [ $(mise set | wc -l) -gt 1 ] '''
command = 'grep -v "^\s*$" .env | wc -l'
when = ''' test -f .env '''
format = '[$symbol($output )]($style)'
